name: hexlet-check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check code

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: make install
      - run: make lint

      - name: Hexlet project check
        uses: hexlet/project-action@release
